services:
  mysql:
    image: mysql:8.0
    container_name: ewf-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ewf
      MYSQL_USER: admin
      MYSQL_PASSWORD: "123456"
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    command: ["--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_0900_ai_ci"]
    volumes:
      # 自动初始化：容器首次启动会执行 docker-entrypoint-initdb.d 下的 .sql
      - ./sql/mysql_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro


# docker compose up -d
# # 然后把 sql/mysql_schema.sql 导入到 ewf 库（用你常用工具/客户端即可）
